/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1dpbofinal;

/**
 *
 * @author dell
 */
public class main extends javax.swing.JFrame {
    private boolean isbuku = false;
    private boolean update = false;
    /**
     * Creates new form main
     */
    dbConnection con = new dbConnection();
    public main() {
        initComponents();
        TBL_data.setModel(con.readTableAutor());
        LBL_1.setVisible(false);
        LBL_2.setVisible(false);
        LBL_3.setVisible(false);
        LBL_4.setVisible(false);
        TF_input1.setVisible(false);
        TF_input3.setVisible(false);
        TF_input2.setVisible(false);
        TF_input4.setVisible(false);
        BTN_submit.setVisible(false);
        BTN_delete.setVisible(false);
    }
    public void insertData(){
        if(isbuku == false){
            if(!TF_input1.getText().isEmpty() && !TF_input3.getText().isEmpty() && !TF_input2.getText().isEmpty()){
                System.out.println("hehe");
                    String nama = TF_input1.getText();
                    String jumlah = TF_input2.getText();
                    String img = TF_input3.getText();
                    con.query("insert into autor (nama_autor, jumlah_buku, img_autor) values (\"" + nama + "\", "+jumlah+", \"" + img + "\")");
                    TBL_data.setModel(con.readTableAutor());
                }
        }else{
            if(!TF_input1.getText().isEmpty() && !TF_input3.getText().isEmpty() && !TF_input2.getText().isEmpty() && !TF_input4.getText().isEmpty()){
                System.out.println("huhu");
                    String img = TF_input1.getText();
                    String penerbit = TF_input2.getText();
                    String autor = TF_input3.getText();
                    String desc = TF_input4.getText();
                    con.query("insert into buku (img_buku, penerbit_buku, autor_buku, Desc_buku) values (\""+img
                            +"\", \""+penerbit+"\", "+autor+", \""+desc+"\")");
                    TBL_data.setModel(con.readTableBuku());
                }
        }
       
    }
    public void updateData(){
        if(isbuku == false){
            int row = TBL_data.getSelectedRow();
            String id = (TBL_data.getModel().getValueAt(row, 0).toString());
            
            
            String nama = TF_input1.getText();
            String jumlah = TF_input2.getText();
            String img = TF_input3.getText();
            con.query("update autor set nama_autor=\"" + nama + "\", jumlah_buku = "+jumlah+", img_autor=\"" + img + "\" where id_autor=\"" + id + "\" ");
            TBL_data.setModel(con.readTableAutor());
        }else{
            int row = TBL_data.getSelectedRow();
           String id = (TBL_data.getModel().getValueAt(row, 0).toString());
            
           String img = TF_input1.getText();
                    String penerbit = TF_input2.getText();
                    String autor = TF_input3.getText();
                    String desc = TF_input4.getText();
            con.query("update buku set img_buku=\"" + img + "\", penerbit_buku = \"" + penerbit + "\", autor_buku="+autor+", Desc_buku=\"" + desc + "\" where id_buku=\"" + id + "\"");
            TBL_data.setModel(con.readTableBuku());
        }
    }
     public void deleteData(){
        if(isbuku == false){
            int row = TBL_data.getSelectedRow();
            String id = (TBL_data.getModel().getValueAt(row, 0).toString());
            
          
            con.query("delete from autor where id_autor=\"" + id + "\" ");
            TBL_data.setModel(con.readTableAutor());
        }else{
            int row = TBL_data.getSelectedRow();
           String id = (TBL_data.getModel().getValueAt(row, 0).toString());
    
            con.query("delete from buku where id_buku=\"" + id + "\"");
            TBL_data.setModel(con.readTableBuku());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BTN_switch = new javax.swing.JButton();
        BTN_add = new javax.swing.JButton();
        LBL_1 = new javax.swing.JLabel();
        TF_input1 = new javax.swing.JTextField();
        LBL_2 = new javax.swing.JLabel();
        TF_input3 = new javax.swing.JTextField();
        LBL_3 = new javax.swing.JLabel();
        TF_input2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_data = new javax.swing.JTable();
        LBL_4 = new javax.swing.JLabel();
        TF_input4 = new javax.swing.JTextField();
        BTN_submit = new javax.swing.JButton();
        BTN_delete = new javax.swing.JButton();
        BTN_Update = new javax.swing.JButton();

        jButton1.setText("Switch");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTN_switch.setText("Switch");
        BTN_switch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_switchActionPerformed(evt);
            }
        });

        BTN_add.setText("Add");
        BTN_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_addActionPerformed(evt);
            }
        });

        LBL_1.setText("Nama Autor");

        LBL_2.setText("Jumlah Buku");

        LBL_3.setText("URL Image");

        TF_input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_input2ActionPerformed(evt);
            }
        });

        TBL_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TBL_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBL_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBL_data);

        LBL_4.setText("Desc Buku");

        BTN_submit.setText("Submit");
        BTN_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_submitActionPerformed(evt);
            }
        });

        BTN_delete.setText("Delete");
        BTN_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_deleteActionPerformed(evt);
            }
        });

        BTN_Update.setText("Update");
        BTN_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(LBL_3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBL_1)
                                    .addComponent(LBL_2)
                                    .addComponent(LBL_4))
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BTN_switch)
                                .addGap(67, 67, 67)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_input4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(TF_input3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BTN_delete))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(BTN_add)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TF_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TF_input2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(BTN_submit))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(BTN_Update))))))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN_switch)
                            .addComponent(BTN_add)
                            .addComponent(BTN_Update))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_1)
                            .addComponent(TF_input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_2)
                            .addComponent(TF_input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(BTN_submit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_3)
                    .addComponent(TF_input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_4)
                    .addComponent(TF_input4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(373, 373, 373))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_switchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_switchActionPerformed
        // TODO add your handling code here:
        if(isbuku == false){
            TBL_data.setModel(con.readTableBuku());
            isbuku = true;
            LBL_1.setText("nama_autor");
            LBL_2.setText("jumlah_buku");
            LBL_3.setText("img_autor");
            LBL_4.setVisible(false);
        }else{
            TBL_data.setModel(con.readTableAutor());
            LBL_1.setText("img_buku");
            LBL_2.setText("penerbit_buku");
            LBL_3.setText("autor_buku");
            LBL_4.setText("Desc_buku");
            LBL_4.setVisible(true);
            isbuku = false;
        }
    }//GEN-LAST:event_BTN_switchActionPerformed

    private void TF_input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_input2ActionPerformed

    private void BTN_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_addActionPerformed
        // TODO add your handling code here:
        if(isbuku == false){
            LBL_1.setVisible(true);
            LBL_2.setVisible(true);
            LBL_3.setVisible(true);
            LBL_4.setVisible(false);
            TF_input1.setVisible(true);
            TF_input3.setVisible(true);
            TF_input2.setVisible(true);
            TF_input4.setVisible(false);
            LBL_1.setText("nama_autor");
            LBL_2.setText("jumlah_buku");
            LBL_3.setText("img_autor");
            BTN_submit.setVisible(true);
          
        }else{
            LBL_1.setVisible(true);
            LBL_2.setVisible(true);
            LBL_3.setVisible(true);
            LBL_4.setVisible(true);
            TF_input1.setVisible(true);
            TF_input3.setVisible(true);
            TF_input2.setVisible(true);
            BTN_submit.setVisible(true);
            TF_input4.setVisible(true);
            LBL_1.setText("img_buku");
            LBL_2.setText("penerbit_buku");
            LBL_3.setText("autor_buku");
            LBL_4.setText("Desc_buku");

        }
        BTN_submit.setText("Submit");
         BTN_delete.setVisible(false);
         update = false;
    }//GEN-LAST:event_BTN_addActionPerformed

    private void TBL_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBL_dataMouseClicked
        // TODO add your handling code here:
        
        int row = TBL_data.getSelectedRow();
        if(isbuku == false){
            String nama = (TBL_data.getModel().getValueAt(row, 1).toString());
            String jumlah = (TBL_data.getModel().getValueAt(row, 2).toString());
            String img = (TBL_data.getModel().getValueAt(row, 3).toString());
            TF_input1.setText(nama);
            TF_input2.setText(jumlah);
            TF_input3.setText(img);
            
        }else{
             String nama = (TBL_data.getModel().getValueAt(row, 1).toString());
            String jumlah = (TBL_data.getModel().getValueAt(row, 2).toString());
            String img = (TBL_data.getModel().getValueAt(row, 3).toString());
            String desc = (TBL_data.getModel().getValueAt(row, 4).toString());
            TF_input1.setText(nama);
            TF_input2.setText(jumlah);
            TF_input3.setText(img);
            TF_input4.setText(desc);
        }
        
        BTN_delete.setVisible(true);
    }//GEN-LAST:event_TBL_dataMouseClicked

    private void BTN_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_UpdateActionPerformed
        // TODO add your handling code here:
         if(isbuku == false){
            LBL_1.setVisible(true);
            LBL_2.setVisible(true);
            LBL_3.setVisible(true);
            LBL_4.setVisible(false);
            TF_input1.setVisible(true);
            TF_input3.setVisible(true);
            TF_input2.setVisible(true);
            TF_input4.setVisible(false);
            BTN_submit.setVisible(true);
            LBL_1.setText("nama_autor");
            LBL_2.setText("jumlah_buku");
            LBL_3.setText("img_autor");
            
        }else{
            LBL_1.setVisible(true);
            LBL_2.setVisible(true);
            LBL_3.setVisible(true);
            LBL_4.setVisible(true);
            TF_input1.setVisible(true);
            TF_input3.setVisible(true);
            TF_input2.setVisible(true);
            BTN_submit.setVisible(true);
            TF_input4.setVisible(true);
            LBL_1.setText("img_buku");
            LBL_2.setText("penerbit_buku");
            LBL_3.setText("autor_buku");
            LBL_4.setText("Desc_buku");
            
        }
         BTN_submit.setText("Update");
         BTN_delete.setVisible(true);
         update = true;
    }//GEN-LAST:event_BTN_UpdateActionPerformed

    private void BTN_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_submitActionPerformed
        // TODO add your handling code here:
        if(update = true){
            updateData();
        }else{
            insertData();
        }
    }//GEN-LAST:event_BTN_submitActionPerformed

    private void BTN_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_deleteActionPerformed
        // TODO add your handling code here:
        deleteData();
    }//GEN-LAST:event_BTN_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Update;
    private javax.swing.JButton BTN_add;
    private javax.swing.JButton BTN_delete;
    private javax.swing.JButton BTN_submit;
    private javax.swing.JButton BTN_switch;
    private javax.swing.JLabel LBL_1;
    private javax.swing.JLabel LBL_2;
    private javax.swing.JLabel LBL_3;
    private javax.swing.JLabel LBL_4;
    private javax.swing.JTable TBL_data;
    private javax.swing.JTextField TF_input1;
    private javax.swing.JTextField TF_input2;
    private javax.swing.JTextField TF_input3;
    private javax.swing.JTextField TF_input4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
